spring:
  application:
    name: gateway-service
  config:
    import: nacos:gateway-service-dev.yml
    redis:
      port: 6379
      host: localhost
      password: 123456
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': #匹配所有请求
           allowed-origins: "*"
           allowed-methods:
             - GET
             - POST
             - PUT
             - DELETE
      discovery:
        locator:
          enabled: true #开启路由注册
      routes:
        - id: order-service #路由ID 保证唯一 建议配合服务名
          uri: lb://order-service #匹配提供服务的路由地址
          predicates:
            - Path=/order/** #断言，路径相匹配进行路由
          filters:
            - StripPrefix=1
        - id: point-server #路由ID 保证唯一 建议配合服务名
          uri: lb://point-server #匹配提供服务的路由地址
          predicates:
            - Path=/point/** #断言，路径相匹配进行路由
          filters:
            - StripPrefix=1
        - id: user-service #路由ID 保证唯一 建议配合服务名
          uri: lb://user-service #匹配提供服务的路由地址
          predicates:
            - Path=/user/** #断言，路径相匹配进行路由
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848

    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000

# Feign Client配置
feign:
  client:
    config:
      point-server:  # 这里要跟服务名一致
        connect-timeout: 5000
        read-timeout: 5000
# 日志配置
logging:
  level:
    org.huangge.pointserver: DEBUG
    com.alibaba.nacos: INFO


